language: go

go:
    - 1.8
    - tip

go_import_path: github.com/v3io/http_blaster
env:
  global:
    - VERSION=$(echo $TRAVIS_TAG)
before_deploy:
  - "GOOS=linux  GOARCH=amd64 go build -o http_blaster-${VERSION}-linux-amd64"
  - "GOOS=darwin GOARCH=amd64 go build -o http_blaster-${VERSION}-darwin-amd64"
deploy:
    provider: releases
    api_key:
    secure: "zCsLNOJWu3TFvtV6OBMKGeEHm5VB767KMGenfHRGw2wwEkeWrhGRSgHQ8ueqPMaRtwvEpxLn3RjZ3Z+H5fcbBB+t5rwyRy6RyoVtPAnqTaFbWxjrEysM/742KDyHxAIGfQzPsu3lcEt/lC9cnFDwFWo6NLNwpiJRnnC8o8LWSAXheOJXrzv/2pzauUaps5dcLGSONhKszj+tSkr6hUUUNrMJ3lTarj7rYAfGC3/jzDIDy8iYrdmyDAJpUxHVqk6C5gVoqhp03r/wFY1Eem+plyCleoF7fyUPPdvTOlzqoa66nQi/7lkB9hxuoMwDEuf12Q4m3KGKAMtsOWNC+Q0dXQ09QdZjOxpnFv+hPjY3E+R0e5JirvKGCBLdZYYMlE77CuXorYHz5z5ipdYRAb3fE/1Kp07815ENIERRViRF9YcGnPizJcwoqq2/hHksTBojwYdclvA8EoghkUTtSu7MFSAfJvhl2nxRFpKFHFq/qxPAIrX3OBqt2INuwG2+qQjAv2oHNau1KNBWDPA+z+8wK5EA9G6UVGISUw+urBznz8y/I4rDgC9ZsbyGhbHaoV4kOmMnCIjBJhRCpdkVWGaBgNBFWU85ZcEAKbtfNlts2euCdRxQIUuJxHUelUvsGgaqJZ2UOm1PC+Grp5VJkJNBABrVdbK7QsEZyoRXRcA4/MU="    file:
      - "http_blaster-$VERSION-darwin-amd64"
      - "http_blaster-$VERSION-linux-amd64"
    skip_cleanup: true
    on:
        tags: true
