language: go

go:
    - 1.8
    - tip

go_import_path: github.com/v3io/http_blaster
env:
  global:
    - VERSION=$(echo $TRAVIS_TAG)
before_deploy:
  - "GOOS=linux  GOARCH=amd64 go build -o http_blaster-${VERSION}-linux-amd64"
  - "GOOS=darwin GOARCH=amd64 go build -o http_blaster-${VERSION}-darwin-amd64"
deploy:
    provider: releases
    api_key:
      secure: zUhmoUT6f25LVqMHVx1taBY+4ljHDUiDY5ItoTIN/AUCVz2VaPgVV5Pswg+HW2s/98d7XmvwBTETSyRye6/rgS98RguPwbvKAi1ie9JI6rwy0cxFGC+MhTc+Uup0KRJHys8CFArpOPAiO26VdjN+q8+VQuZKqRF++GGkjQBfALR5Q/uXfbJ7gf+dXYpY6ylGgDDbVrY9o9hB6wWxwiYT819BOKFjGnyMDKk0b+hYg4dyeDfYWrz0yrhRffbEcTyUo0ZxHniIR16adq2VJEh+qivnctGZWhQdbdNVjgVqf6s8+Qb8+sCNC/Mb1Em7HKchIoNqCfaKRZB/FmOIXeiqgV0UTcQrJnvAd8LCXKJEFsQs5femv2t8oaGkMTr5WEAIjFMi33GTWgSXY1pkSNOCU7eH+nBbaEDJcdpPihGs3o/gDM8hH0Bg7O++9Ac9lJbzb9kAL6nMfMF/bNEIP0Y6Hgu5yl6wkLK6B3+zhbs0bwjQcYfysf3NPmsCdMl/rULpL9HqpbBCxBENeZUyNKkNx4+9Z/QG52OZayyYuebAZykp3Ilshplb83MeQYjubxKJOofkbEVWWMvcBk2UiyTrWmtP2pYmKap8b0UJcWoPYmjNIlJAB7Yn7WL06RXZFgjmrxV8J703K1CjsslQASj3o6g08giHyQb+khdCAspNVm0=
    file:
      - "http_blaster-$VERSION-darwin-amd64"
      - "http_blaster-$VERSION-linux-amd64"
    skip_cleanup: true
    on:
        tags: true
