language: go

go:
    - 1.8
    - tip

go_import_path: github.com/v3io/http_blaster
env:
  global:
    - VERSION=$(echo $TRAVIS_TAG)
before_deploy:
  - "GOOS=linux  GOARCH=amd64 go build -o http_blaster-${VERSION}-linux-amd64"
  - "GOOS=darwin GOARCH=amd64 go build -o http_blaster-${VERSION}-darwin-amd64"
deploy:
    provider: releases
    api_key:
      secure: zQpel8+qqCNMm2kLwqSC8cvn+980sDX3E0KMsphCWMNnPny+7gbfa+63R3bXnSqSpYB66QDOO8xpZfUJRFgr7VMkUPwwyhlPAvB5N6rYVHaDOaGXdgia90smv35FQ7/DmYmBGvF53DRcFZk3+/xxGkiUzyG88h9NT9Q2huLwqj0cICcYX5tJKd7B+yE5QRceu/lfAQqDjxa2843AYylPsGTvWaoyXGWpn3arZS4YqE2DqWDzb/ul6WcC0IVgpuaoD74Ztk6zcx/wSuVSTWZN34fAa6BCjNHVRutTQ2f/zJ0lzTp3yxGuaJ7tZt7AxAqOsjouT0WB2+KckaKnB0GtOwuBhJZ5Op031VpuWEMBacj4sSc7e539kVZ89oJc9ZB1GjBfsQVw6OS1fq67gvTv+p8y5hZ6NJVFMALBRySxjEUJmFGCscYAdnBFbvTihuNusqdtpl9vTF3BvBWTkTk8CiPGJTpVvsYqzMgWL+SQ4jYGvtnWMDQBtoOUyJhmoZzSH5r2sP9OaPZz0acs0whOL5rAKD1Ko2AKUG6GH66+UzG3hjZZjDGAXTuC3FeE/RFdJagFKQrciDHWb70LaKSj+8nmwW2EoB6VHAFTIJdKYWST+pStVVT+RuIp6NFoTKRHOrLAOxtFqnw6cZgT4OnFdpQJI/1Kkh+E07A6WJ6aybo=
    file:
      - "http_blaster-$VERSION-darwin-amd64"
      - "http_blaster-$VERSION-linux-amd64"
    skip_cleanup: true
    on:
        tags: true
